#!/bin/bash -x

go test -count=1 ./... -coverprofile=/dev/null
go test -count=1 ./... -coverprofile=/dev/null -coverpkg=github.com/nickgrim/coverpkgtest/bar
go test -count=1 ./... -coverprofile=/dev/null -coverpkg=github.com/nickgrim/coverpkgtest/foo
go test -count=1 ./... -coverprofile=/dev/null -coverpkg=github.com/nickgrim/coverpkgtest/foo,github.com/nickgrim/coverpkgtest/bar
go test -count=1 ./... -coverprofile=/dev/null -coverpkg=./...
